start_ac:
  description: "Start the vehicle's AC system"
  fields:
    vin:
      description: "Vehicle Identification Number"
      example: "1HGCM82633A123456"

stop_ac:
  description: "Stop the vehicle's AC system"
  fields:
    vin:
      description: "Vehicle Identification Number"
      example: "1HGCM82633A123456"

start_ac_with_settings:
  description: "Start the vehicle's AC system with temperature and fan settings."
  fields:
    vin:
      description: "Vehicle Identification Number"
      example: "1HGCM82633A123456"
    temperature:
      description: "Desired temperature in degrees Celsius"
      example: 22.5
    fan_speed:
      description: "Fan speed level (e.g., 1-7)"
      example: 3

start_charging:
  description: "Start the vehicle charging process"
  fields:
    vin:
      description: "Vehicle Identification Number"
      example: "1HGCM82633A123456"

stop_charging:
  description: "Stop the vehicle charging process"
  fields:
    vin:
      description: "Vehicle Identification Number"
      example: "1HGCM82633A123456"

start_battery_heating:
  description: "Start the vehicle battery heating process"
  fields:
    vin:
      description: "Vehicle Identification Number"
      example: "1HGCM82633A123456"

stop_battery_heating:
  description: "Stop the vehicle battery heating process"
  fields:
    vin:
      description: "Vehicle Identification Number"
      example: "1HGCM82633A123456"

set_target_soc:
  description: "Set the target SOC (State of Charge) for the vehicle."
  fields:
    vin:
      description: "Vehicle Identification Number"
      example: "1HGCM82633A123456"
    target_soc:
      description: "Desired target SOC percentage (10-100)"
      example: 80

lock_vehicle:
  description: "Lock the vehicle"
  fields:
    vin:
      description: "Vehicle Identification Number"
      example: "1HGCM82633A123456"

unlock_vehicle:
  description: "Unlock the vehicle"
  fields:
    vin:
      description: "Vehicle Identification Number"
      example: "1HGCM82633A123456"

open_tailgate:
  description: "Open the vehicle's tailgate"
  fields:
    vin:
      description: "Vehicle Identification Number"
      example: "1HGCM82633A123456"

trigger_alarm:
  description: "Trigger the vehicle's alarm"
  fields:
    vin:
      description: "Vehicle Identification Number"
      example: "1HGCM82633A123456"

control_rear_window_heat:
  description: "Control the rear window heat"
  fields:
    vin:
      description: "Vehicle Identification Number"
      example: "1HGCM82633A123456"
    action:
      description: "Turn on (true) or off (false)"
      example: true

control_heated_seats:
  description: "Control the heated seats"
  fields:
    vin:
      description: "Vehicle Identification Number"
      example: "1HGCM82633A123456"
    action:
      description: "Turn on (true) or off (false)"
      example: true

start_front_defrost:
  description: "Start the front defrost system of the vehicle"
  fields:
    vin:
      description: "Vehicle Identification Number"
      example: "1HGCM82633A123456"